name: Test

on:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches:
      - "*"
    paths:
      - "**test.yml"
      - "**.rkt"
      - "**.scrbl"
  pull_request:
    branches:
      - "*"
    paths:
      - "**.rkt"
      - "**.scrbl"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-variant: ["CS"]
        racket-version: ["stable", "current"]
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: "x64" # (x64 or x86), ignored on Linux
          distribution: "minimal"
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - run: raco pkg install --auto --skip-installed
      - run: |
          raco test .
          #xvfb-run -a raco test .
